# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-07-29 14:13:44

#  <-  -> 

version: '3.7'
services:
  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '3000:3000'
    volumes:
      - 'grafana:/var/lib/grafana'
    networks:
      grafana: {}
    environment:
      TZ: 'Asia/Shanghai'

volumes:
  grafana:
    name: 'grafana'
networks:
  grafana:
    name: 'grafana'
