# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-10-14 14:32:04

# Description: The official Grafana docker container

version: '3.7'
services:
  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '3000:3000'
    volumes:
      - 'grafana:/var/lib/grafana'
    networks:
      data: {}
    environment:
      TZ: 'Asia/Shanghai'


volumes:
  grafana:
    name: 'grafana'


networks:
  data:
    name: 'data-display'
