# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 10:44:30

# 数据库 <- oracle -> Oracle 12c EE image with web management console.
# username: system ; password: oracle

version: '3.7'
services:
  oracle:
    image: 'absolutapps/oracle-12c-ee'
    container_name: 'oracle'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: true
    ports:
      - '1521:1521'
      - '5500:5500'
      - '8080:8080'
    volumes:
      - 'oracle:/u01/app/oracle'
    environment:
      TZ: 'Asia/Shanghai'
volumes:
  oracle:
    name: 'oracle'
