# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 14:23:39

# Description: The PostgreSQL object-relational database system provides reliability and data integrity

version: '3.7'
services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgres/data'
      - 'postgres:/var/lib/postgresql/data'
    networks:
      postgres: {}
    environment:
      TZ: 'Asia/Shanghai'
      POSTGRES_DB: 'postgres'     # 默认数据库名
      POSTGRES_USER: 'postgres'   # 默认用户名
      POSTGRES_PASSWORD: 'postgres'
    labels:
      servicename: 'postgres'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  postgres:
    name: 'postgres'


networks:
  postgres:
    name: 'postgres'
