# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 14:23:39

# 数据库 - postgres

version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped     # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres     # 默认数据库名
      POSTGRES_USER: postgres   # 默认用户名
      POSTGRES_PASSWORD: postgres
