# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-10-14 14:26:56

# Description: Chronograf is a visualization tool for time series data in InfluxDB

version: '3.7'
services:
  chronograf:
    image: 'chronograf'
    container_name: 'chronograf'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '8888:8888'
    volumes:
      - 'chronograf:/var/lib/chronograf'
    networks:
      data: {}
    environment:
      TZ: 'Asia/Shanghai'


volumes:
  chronograf:
    name: 'chronograf'
networks:
  data:
    name: 'data-display'
