# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-23 10:18:07

# 运行Python flask app <- python-flask-app-on-docker -> self-defined

version: '3.7'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      TZ: 'Asia/Shanghai'
  redis:
    image: 'redis'
