# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-06-20 17:22:55

#  <-  -> 

version: '3.7'
services:
  tensorflow:
    image: 'tensorflow/tensorflow'
    container_name: 'tensorflow'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    stdin_open: true
    tty: true
    ports:
      - '8888:8888'
    networks:
      tensorflow: {}
    environment:
      TZ: 'Asia/Shanghai'

networks:
  tensorflow:
    name: 'tensorflow'
