# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-11-08 14:30:10

# Description: An open-source time-series database optimized for fast ingest and complex queries. Engineered up from PostgreSQL, packaged as an extension
# 默认用户名：postgres

version: '3.7'
services:
  timescaledb:
    image: 'timescale/timescaledb:latest-pg11'
    container_name: 'timescaledb'
    restart: 'unless-stopped'       # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'timescaledb:/var/lib/postgresql/data'
    networks:
      timescaledb: {}
    environment:
      TZ: 'Asia/Shanghai'
      POSTGRES_PASSWORD: 'postgres'
    labels:
      servicename: 'timescaledb'
    logging:
      driver: 'json-file'    # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  timescaledb:
    name: 'timescaledb'


networks:
  timescaledb:
    name: 'timescaledb'
