# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 11:09:34

# docker <- portainer -> Making Docker management easy. https://portainer.io

version: '3.7'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped     # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    environment:
      TZ: Asia/Shanghai
volumes:
  portainer:
    name: portainer
