# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-09 10:38:59

# 游戏 <- hollywood -> 终端相关

version: '3.7'
services:
  hollywood:
    image: jess/hollywood
    container_name: hollywood
    restart: unless-stopped     # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    environment:
      TZ: Asia/Shanghai
