# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-07-29 14:13:44

# Database <- Influxdb -> influxdb、chronograf、grafana三件套

version: '3.7'
services:
  influxdb:
    image: 'influxdb'
    container_name: 'influxdb'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '8086:8086'
    volumes:
      - 'influxdb:/var/lib/influxdb'
    networks:
      suit: {}
    environment:
      TZ: 'Asia/Shanghai'

  chronograf:
    image: 'chronograf'
    container_name: 'chronograf'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '8888:8888'
    volumes:
      - 'chronograf:/var/lib/chronograf'
    networks:
      suit: {}
    environment:
      TZ: 'Asia/Shanghai'

  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '3000:3000'
    volumes:
      - 'grafana:/var/lib/grafana'
    networks:
      suit: {}
    environment:
      TZ: 'Asia/Shanghai'


volumes:
  influxdb:
    name: 'influxdb'
  chronograf:
    name: 'chronograf'
  grafana:
    name: 'grafana'


networks:
  suit:
    name: 'three-piece'
