# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-10-23 09:00:00

# Description: InfluxDB is an open source time series database for recording metrics, events, and analytics
#              Chronograf is a visualization tool for time series data in InfluxDB
#              The official Grafana docker container


version: '3.7'
services:
  influxdb:
    image: 'influxdb'
    container_name: 'influxdb'
    restart: 'unless-stopped'       # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    volumes:
      - 'influxdb:/var/lib/influxdb'
    networks:
      data: {}
    environment:
      TZ: 'Asia/Shanghai'
      INFLUXDB_DB: 'influxdb'
      INFLUXDB_USER: 'influxdb'
      INFLUXDB_USER_PASSWORD: 'influxdb'
    labels:
      servicename: 'influxdb'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'

  chronograf:
    image: 'chronograf'
    container_name: 'chronograf'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - 'chronograf:/var/lib/chronograf'
    networks:
      data: {}
    environment:
      TZ: 'Asia/Shanghai'
      INFLUXDB_URL: 'http://influxdb:8086'
      INFLUXDB_USERNAME: 'influxdb'
      INFLUXDB_PASSWORD: 'influxdb'
    labels:
      servicename: 'chronograf'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'

  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - 'grafana:/var/lib/grafana'
      - './grafana/plugins:/var/lib/grafana/plugins'
    networks:
      data: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'grafana'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  influxdb:
    name: 'musketeer_influxdb'
  chronograf:
    name: 'musketeer_chronograf'
  grafana:
    name: 'musketeer_grafana'


networks:
  data:
    name: 'influxdb-chronograf-grafana'
