# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-15 09:40:43

# docker <- watchtower -> Watches your containers and automatically restarts them whenever their image is refreshed.

version: '3.7'
services:
  watchtower:
    image: 'v2tec/watchtower'
    container_name: 'watchtower'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      watchtower: {}
    environment:
      TZ: 'Asia/Shanghai'
      WATCHTOWER_POLL_INTERVAL: '86400'      # 间隔1天
      WATCHTOWER_CLEANUP: 'true'

networks:
  watchtower:
    name: 'watchtower'
