# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 14:15:59

# 数据库 <- redis -> Redis is an open source key-value store that functions as a data structure server

version: '3.7'
services:
  redis:
    image: 'redis'
    container_name: 'redis'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    environment:
      TZ: 'Asia/Shanghai'
volumes:
  redis:
    name: 'redis'
