# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-07-29 14:13:44

# Description: InfluxDB is an open source time series database for recording metrics, events, and analytics

version: '3.7'
services:
  influxdb:
    image: 'influxdb'
    container_name: 'influxdb'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '8086:8086'
    volumes:
      - 'influxdb:/var/lib/influxdb'
    networks:
      data: {}
    environment:
      TZ: 'Asia/Shanghai'


volumes:
  influxdb:
    name: 'influxdb'


networks:
  data:
    name: 'data-display'
