# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 11:15:44

# Description: RabbitMQ is an open source multi-protocol messaging broker

version: '3.7'
services:
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'rabbitmq'
    restart: 'unless-stopped'    # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq'
    networks:
      rabbitmq: {}
    environment:
      TZ: 'Asia/Shanghai'
      hostname: 'YJ-Arch'
    labels:
      servicename: 'rabbitmq'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  rabbitmq:
    name: 'rabbitmq'


networks:
  rabbitmq:
    name: 'rabbitmq'
