# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2020-11-25 16:46:32

# Description:

version: '3'
services:
  sonarqube:
    image: 'sonarqube'
    container_name: 'sonarqube'
    hostname: 'sonarqube-docker'
    restart: 'unless-stopped'  # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '9000:9000'
    # volumes:
    #   - ':'
    networks:
      sonarqube: {}
    environment:
      TZ: 'Asia/Shanghai'
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    labels:
      servicename: 'sonarqube'
    logging:
      driver: 'json-file'      # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


# volumes:
#   sonarqube:
#     name: 'sonarqube'


networks:
  sonarqube:
    name: 'sonarqube'
